// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa9l5VHlmu6Uh4d5fVdoapie_nAmJmupo',
    appId: '1:129251174393:web:626dcd82c53c9603a5bf28',
    messagingSenderId: '129251174393',
    projectId: 'rftv-mobile',
    authDomain: 'rftv-mobile.firebaseapp.com',
    storageBucket: 'rftv-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQk4HXsGFsdHJHxaTN0n8aYmL-E7PdebY',
    appId: '1:129251174393:android:800be87a2deb35bca5bf28',
    messagingSenderId: '129251174393',
    projectId: 'rftv-mobile',
    storageBucket: 'rftv-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfjJqnTrRZvMifnow6hwfQrRRyw9YMq8o',
    appId: '1:129251174393:ios:478cf4c5dcc06f9aa5bf28',
    messagingSenderId: '129251174393',
    projectId: 'rftv-mobile',
    storageBucket: 'rftv-mobile.firebasestorage.app',
    iosBundleId: 'com.rftv.rftvMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfjJqnTrRZvMifnow6hwfQrRRyw9YMq8o',
    appId: '1:129251174393:ios:478cf4c5dcc06f9aa5bf28',
    messagingSenderId: '129251174393',
    projectId: 'rftv-mobile',
    storageBucket: 'rftv-mobile.firebasestorage.app',
    iosBundleId: 'com.rftv.rftvMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa9l5VHlmu6Uh4d5fVdoapie_nAmJmupo',
    appId: '1:129251174393:web:d3031fa0883e9b36a5bf28',
    messagingSenderId: '129251174393',
    projectId: 'rftv-mobile',
    authDomain: 'rftv-mobile.firebaseapp.com',
    storageBucket: 'rftv-mobile.firebasestorage.app',
  );
}
